service: hello-world
provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
